name: Summarizer CI/CD

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to use as cache source
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest || true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile.prod
          pull: true
          push: true
          tags: latest
      # - name: Build image
      #   run: |
      #     docker build \
      #       --cache-from ${{ env.IMAGE_NAME }}:latest \
      #       --tag ${{ env.IMAGE_NAME }}:latest \
      #       --file ./project/Dockerfile.prod \
      #       "./project"
      # - name: Push image
      #   run: |
      #     docker push ${{ env.IMAGE_NAME }}:latest
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        # with:
        #   ref: main
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to use as cache source
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest || true
      - name: Build image
        run: |
          docker build \
            --cache-from ${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --file ./project/Dockerfile.prod \
            "./project"
      - name: Run tests
        run: |
          docker run \
            -d \
            --name summarizer \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e DATABASE_URL=sqlite://sqlite.db \
            -e DATABASE_TEST_URL=sqlite://sqlite.db \
            -p 5003:8765 \
            ${{ env.IMAGE }}:latest
      - name: Pytest
        run: docker exec summarizer python -m pytest .
      - name: Flake8
        run: docker exec summarizer python -m flake8 .
      - name: Black
        run: docker exec summarizer python -m black . --check
      - name: isort
        run: docker exec summarizer python -m isort . --check-only