name: Summarizer CI/CD

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/summarizer

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build_and_push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile.prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        # with:
        #   ref: main
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to use as cache source
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest || true
      - name: Run tests
        run: |
          docker run \
            -d \
            --name summarizer \
            -e PORT=8765 \
            -e ENVIRONMENT=dev \
            -e DATABASE_URL=sqlite://sqlite.db \
            -e DATABASE_TEST_URL=sqlite://sqlite.db \
            -p 5003:8765 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Pytest
        run: docker exec summarizer python -m pytest .
      - name: Flake8
        run: docker exec summarizer python -m flake8 .
      - name: Black
        run: docker exec summarizer python -m black . --check
      - name: isort
        run: docker exec summarizer python -m isort . --check-only